### PR TITLE
add gil

### PR DESCRIPTION
**Pull request by alekstheod**

### CODE REVIEW

**Comment by nelhage** [comment]
This failing CI. Does gil exist in boost 1.67? I suspect adding it and upgrading boost separately will have the best luck, and I'd much rather merge them as two PRs, as well.

**Comment by alekstheod** [comment]
> This failing CI. Does gil exist in boost 1.67? I suspect adding it and upgrading boost separately will have the best luck, and I'd much rather merge them as two PRs, as well.

Ok I will do it during the weekend. However gil should be in 1.67. I think that build is failing for a different reason. Could you take a look on that? It looks to be one of the existing tests. How does it work on master?

**Comment by alekstheod** [comment]
> > This failing CI. Does gil exist in boost 1.67? I suspect adding it and upgrading boost separately will have the best luck, and I'd much rather merge them as two PRs, as well.
> 
> Ok I will do it during the weekend. However gil should be in 1.67. I think that build is failing for a different reason. Could you take a look on that? It looks to be one of the existing tests. How does it work on master?
> 
> `ERROR: /root/project/test/BUILD:137:1: no such package '@boost//': Malformed input or input contains unmappable characters: /root/.cache/bazel/_bazel_root/2eb6a2bef0acdd4230a3df892228b4cf/external/boost/libs/wave/test/testwave/testfiles/utf8-test-ßµ™∃/file.hpp and referenced by '//:endian'`

btw did you try to build it without a local installation of boost? It looks not to be working. I removed boost and tried to build it but it can't find some headers. So I will try to make it work with a separate pull request. The fix should be to include the .h files in srcs arg so that they are copied to the sandbox.

**Comment by nelhage** [comment]
superseded by #146

**Pull request closed without merging**
