### PR TITLE
Add macOS arm64 build

### PR DESCRIPTION
**Pull request by Vertexwahn**
Add macOS arm64 build

### CODE REVIEW

**Comment by cpsauer** [comment]
@Vertexwahn, seems to me like we should go ahead with this, rather than waiting on ubuntu arm64 with #390 
Thoughts? (Saw you closed)

**Comment by Vertexwahn** [comment]
@cpsauer Yes - let's go ahead here! ;)

**Comment by cpsauer** [comment]
Sweet! Thanks for doing :)
Did you see Nelson's email, btw? Want to make sure it got to you.

**Comment by cpsauer** [comment]
heh, we each commented the same thing on each other's PRs at the exact same time

**Pull request merged**
