### PR TITLE
Switch from archive to release URLs where possible and add mirror for Boost

### PR DESCRIPTION
**Pull request by Vertexwahn**
Boost was mirrored https://github.com/bazelbuild/bazel/issues/18122

### CODE REVIEW

**Comment by cpsauer** [comment]
Thanks for always looking to make things better :)

[Will want to make sure we don't lose Renovate auto-update, though.]

For my learning: Are you seeing big wins from mirroring for the GitHub-hosted URLs? Starting to scope whether mirrors would be worth manual work/breaking auto-update where we've got it.

**Comment by Vertexwahn** [comment]
I have seen in the past problems with downloading Boost. I guess this was before the switch to jfrog was done. But I have also seen several problems with Artifactory in the past ;) - for the other repos I do not know - since I have mirrored them locally and embedded them with  `local_repository` before rules_boost is embedded. But from time to time my CI jobs fail because some server is away for a few minutes.

I was fearing that Dependabot can not handle multiple URLs - not sure what will happen if we merge this PR ;). Maybe https://github.com/renovatebot/renovate is better here - not sure. Could also think about writing a shell script to handle auto updates of release versions, similar as shown here -> https://link.medium.com/XfQe54LY4yb (see Update of libraries) or try to extend Dependabot/Renovate. In a perfect world, Dependabot would be able to handle it ;)

If we have to go for UPDATES or MIRRORs I would prefer UPDATES. Anyways the URL switch from "archive" to "release" URLs should be done.

**Comment by cpsauer** [comment]
Yep. Mostly the same thoughts all around. Definitely positive on move to release where we can + add mirror for Boost, where we're updating manually already (thanks to you!). Happy to merge them all in as part of this PR. No need to split or anything.

For the GitHub deps, the thing is, even if Renovate already auto-updates the mirror urls, the mirror won't work until someone manually asks Bazel to do an update, right? I'm guessing GitHub is probably already stable enough -> not worth the manual work to mirror, but I could be wrong.

**Comment by cpsauer** [comment]
Oh, actually, it looks like [Boost might also now be available on GitHub](https://github.com/boostorg/boost/releases) if we want to get automated PRs for Boost, automerging iff CI passes? What do you think?

(If so, just change link to GitHub and add to renovate.json5. Perhaps we should just whitelist everything rather than require manually changes, since everything is whitelisted. I think changing matchPackageNames -> `matchPackagePatterns = [""],` should do it.)

**Comment by cpsauer** [comment]
Oh bummer. Any idea what's up?

**Comment by Vertexwahn** [comment]
```
    maybe(
        http_archive,
        name = "boost",
        build_file = "@com_github_nelhage_rules_boost//:boost.BUILD",
        #patch_cmds = ["rm -f doc/pdf/BUILD"],
        #patch_cmds_win = ["Remove-Item -Force doc/pdf/BUILD"],
        sha256 = "b62bd839ea6c28265af9a1f68393eda37fab3611425d3b28882d8e424535ec9d",
        strip_prefix = "boost-1.82.0",
        url = "https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.gz"
    )
```

->

```
ERROR: /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/cc4590d5a577b17209b16bde722a0d52/external/boost/BUILD.bazel:697:14: Middleman _middlemen/@boost_S_S_Ccore-cc_library-compile failed: missing input file '@boost//:boost/checked_delete.hpp'
ERROR: /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/cc4590d5a577b17209b16bde722a0d52/external/boost/BUILD.bazel:787:14: Middleman _middlemen/@boost_S_S_Cdetail-cc_library-compile failed: missing input file '@boost//:boost/blank.hpp'
ERROR: /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/cc4590d5a577b17209b16bde722a0d52/external/boost/BUILD.bazel:787:14: Middleman _middlemen/@boost_S_S_Cdetail-cc_library-compile failed: missing input file '@boost//:boost/blank_fwd.hpp'
ERROR: /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/cc4590d5a577b17209b16bde722a0d52/external/boost/BUILD.bazel:2001:14: Middleman _middlemen/@boost_S_S_Cstatic_Uassert-cc_library-compile failed: missing input file '@boost//:boost/detail/workaround.hpp'
ERROR: /home/vertexwahn/.cache/bazel/_bazel_vertexwahn/cc4590d5a577b17209b16bde722a0d52/external/boost/BUILD.bazel:697:14: Middleman _middlemen/@boost_S_S_Ccore-cc_library-compile failed: missing input file '@boost//:boost/type.hpp'
...
```

**Comment by Vertexwahn** [comment]
@cpsauer Switched from "archive" to "release" where possible and added boost mirror - ready to merge - in the future we should use GitHub`s boost - and in the far future we should move the BUILD files directly to boost ;)

**Comment by cpsauer** [comment]
Looks great to me. Thanks @Vertexwahn. Merging.

**Pull request merged**
