### PR TITLE
switch to boost 1.69

### PR DESCRIPTION
**Pull request by alekstheod**

### CODE REVIEW

**Comment by alekstheod** [comment]
Could we switch to a newest version of bazel? 0.25?

**Comment by nelhage** [comment]
Happy to bump bazel! You should be able to edit `.circleci/config.yaml` to change the version we test against.

**Comment by nelhage** [comment]
Ah, I see you already did :)

**Comment by nelhage** [comment]
I'll happily merge this if we can sort out the broken build

**Comment by alekstheod** [comment]
I see several issues when building on my machine.
1) the build is not hermetic due to the fact that lib stacktrace most probably is using your installed version of libbacktrace.
2) there is a dependency to zstd which was introduced in boost 1.69 I guess.
I will try to solve them...

**Comment by alekstheod** [comment]
> I'll happily merge this if we can sort out the broken build

Do you know if there is a bazel rule for make - configure targets? libbacktrace is a make project and configure generates the config.h file which is required to build it...

**Comment by nelhage** [comment]
> Do you know if there is a bazel rule for make - configure targets? libbacktrace is a make project and configure generates the config.h file which is required to build it...

There isn't a standard solution. If the `configure` script is relatively minimal, it's not uncommon to just ship a prebaked `config.h`, since modern platforms have much less diversity than the ones `autoconf` and friends were designed around.

**Comment by nelhage** [comment]
See for instance this config on livegrep that provided a prebaked `config.h` for Google's `sparsehash`: https://github.com/livegrep/livegrep/commit/27e178a9acce99acd545261c098eee46f873f20c

**Comment by nelhage** [comment]
Superseded by #143

**Pull request closed without merging**
