### PR TITLE
Update README.md now that platform_mappings are obsolete in Bazel7

### PR DESCRIPTION
**Pull request by cpsauer**

### CODE REVIEW

**Comment by cpsauer** [comment]
(@nelhage, if there's a way to skip checks to merge docs changes faster, would love if you'd lmk.)

**Comment by cpsauer** [comment]
^ or @nelhage, maybe more generally, could I ask you to see if you can easily/quickly allow the [auto-merge-when-tests-pass merge option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) for this repo? It'd be a super handy time saver, but for whatever reason it doesn't seem to show up in this repo.

**Comment by nelhage** [comment]
Believe it should be enabled now!

**Comment by cpsauer** [comment]
Sweet! Thanks, Nelson!

There wasn't an easy way to whitelist renovate on branch protection was there? 

The accident report on my mind is:
I'd taken to ignoring the large volume of auto-update-boringssl emails because the volume was so high. But then I missed that a CI issue (#520) had prevented boringssl auto-merging for a month and a half. All fixed now. But it'd be nice to change Renovate over to silent-unless-CI-fails-then-PR behavior, since then the emails would have signal: we'd only get pinged when there was something actionable to do. (Reversing #280).

**Comment by nelhage** [comment]
It looks like there's an option (currently disabled) for "Require a pull request before merging"; it appears that with that disabled, but with branch protection on, it's legal to push a branch, wait for CI, and then merge (or push) that branch to `master`. I think that should mean renovate could merge its own branches directly (without the PR spam), as long as they have a passing status check. Is that a workable configuration?

**Comment by cpsauer** [comment]
Sounds promising to me! (Or, if you want to enforce PRs and notifications for all human collaborators (like me & Vertexwahn), I think from GitHub's docs that you can also whitelist renovate under "Allow specified actors to bypass required pull requests", while still keeping pull request otherwise required and status checks always required.)

Want to give that a try and then revert 4dd29ef98696bb646c3450ef32e8d32039bd1f5b (or I can). Either way, lmk :)

**Pull request merged**
