### PR TITLE
feat: use zlib from bcr

### PR DESCRIPTION
**Pull request by finn-ball**
Currently failing CI. We should figure out why and use zlib from bcr.

```
external/rules_boost~~non_module_dependencies~boost/libs/iostreams/src/zlib.cpp:20:10: error: use of private header from outside its module: 'zlib.h' [-Wprivate-header]
#include "zlib.h"   // Jean-loup Gailly's and Mark Adler's "zlib.h" header.
         ^
1 error generated.
```

### CODE REVIEW

**Comment by Vertexwahn** [comment]
Try to use [1.3.1.bcr.1](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/zlib/1.3.1.bcr.1)

**Comment by finn-ball** [comment]
> Try to use [1.3.1.bcr.1](https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/zlib/1.3.1.bcr.1)

same issue - perhaps we need to add a `-Wno-private-error`

**Comment by lalten** [comment]
You could try depending on `@bazel_tools//third_party/zlib` instead for now, which is always available

**Comment by rockwotj** [comment]
Can you patch that file to use a system includes instead of a quoted includes? I believe the includes directive that is used in zlib adds `-isystem`

**Comment by finn-ball** [comment]
we could also try patching BCR with the build file in this repository by replacing this file:
https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/zlib/1.3.1/patches/add_build_file.patch

**Comment by rockwotj** [comment]
The comment in that build file seems to state it's a feature that the header does not leak from a visibility perspective (they explicitly copy to another directory). It really should be a system include

**Pull request closed without merging**
