### PR TITLE
Fix missing symbols when depending on @boost//:test

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by nelhage** [comment]
Hm, that exclude was added in https://github.com/nelhage/rules_boost/pull/43 to fix a specific problem. Does defining `BOOST_TEST_DYN_LINK=0` also prevent this double-definition problem, or do we need to do something else?

Does removing the `#define BOOST_TEST_DYN_LINK` from your test case in #91 change anything?

**Comment by nelhage** [comment]
This branch is failing locally for me with missing symbols in the `//:test` target. Unfortunately CI is down right now while github recovers, but I suspect circle would show the same thing.

**Comment by ktf** [comment]
`BOOST_TEST_DYN_LINK=0` fixes the double definition for me, that's why I actually introduced it. I cannot drop the define from my setup. I will try to look into the failing `//:test`.

**Comment by reltuk** [comment]
For Boost.Test, if a project is using `boost/test/included/...` then it can't link against `libboost_unit_test_framework`. That means the bazel target that exposes `boost/test/incldued/...` shouldn't also expose `libs/test/src/...` object files.

In #147 we added `@boost//:test.a`, which doesn't expose `boost/test/included/...` and is meant for the static linking use case. Hopefully that meets the use case here.

**Comment by reltuk** [comment]
Closing this for now. Please feel free to reopen if using `@boost//:test.a` or `@boost//:test.so` doesn't work as expected.

**Pull request closed without merging**
