### PR TITLE
Revert "Disable PR-free auto update, since branch protection settings…

### PR DESCRIPTION
**Pull request by nelhage**
… prevent it."

This reverts commit 9bba2f542420bffed1500786cbde60ef34dc7b24.

per https://github.com/nelhage/rules_boost/pull/519#issuecomment-1813792314, going to give this a try.

### CODE REVIEW

**Comment by nelhage** [comment]
I feel very confused -- I do not see any of the options to allowlist users or applications in the settings page for this repository. It's possible they do not exist for free tier accounts or outside of organizations or something, but I also can't find any reference to such limitations in the docs.

Screenshot 2023-11-30 at 10-02-02 Settings · Branches · Branch protection rule · nelhage_rules_boost

**Comment by nelhage** [comment]
Ah-ha! Thanks – I hadn't actually encountered the "ruleset" feature at all before! I think that should now be in place.

**Comment by cpsauer** [comment]
Wahoo! Thanks for being willing to give it a go Nelson.

I think this'll be pretty sweet if we can get it to work, silently automating away as much work as possible.

Meanwhile, I tracked down the boringssl issue. It looks like a genuine thing we'll need them to make a call on to resolve, so I filed https://bugs.chromium.org/p/boringssl/issues/detail?id=671. Renovate should automatically do the right thing and hold off on merging until boringssl is back building cleanly, and then, hopefully with these new permissions, get to auto-merging.

**Comment by cpsauer** [comment]
Looks like this worked with https://github.com/nelhage/rules_boost/commit/2a94036b71b406e6bb223605aa267b9c64682291 :) Yay! Thanks, Nelson.

The boringssl folks have pushed a commit fixing the other issue. Should auto-propagate through shortly.

**Pull request merged**
