### PR TITLE
Update to Boost 1.81

### PR DESCRIPTION
**Pull request by gjasny**

### CODE REVIEW

**Comment by cpsauer** [comment]
Hi, @gjasny! Thanks for you contributions and for proposing the update.

It looks like there are some build troubles in the tests that'd prevent a merge; could I ask you to look into those?

Cheers,
Chris

**Comment by gjasny** [comment]
Thanks for notifying. I did not get an email for failed CI stages (like with GitHub Actions).

All is working now.

**Comment by cpsauer** [comment]
Thanks so much for doing! Merging :)

**Comment by cpsauer** [comment]
Seems like it'd be good to turn on auto-notification for CI failure. @gjasny, do you know a good way to do that by any chance?

**Pull request merged**
