### PR TITLE
Turn auto_link off in MSVC compiler

### PR DESCRIPTION
**Pull request by Vertexwahn**
Fixing the issues described here https://github.com/nelhage/rules_boost/issues/112 for boost test filesystem.

### CODE REVIEW

**Comment by pablitens** [comment]
The change should be done in boost/boost.bzl rather than explicitly adding a BOOST_ALL_NO_LIB define for each boost library in BUILD.boost. See how default_copts is implemented in boost/boost.bzl and add an analogous default_defines.

**Comment by Vertexwahn** [comment]
@pablitens I added a analogous default_defines

**Comment by nelhage** [comment]
I assume @Vertexwahn and/or @ztl8702 can confirm this fixes the build on Windows? I'm happy to accept if we have confirmed testing – as mentioned, I don't have a Windows build environment.

As an aside, it looks like Azure pipelines has free Windows CI these days; if either of you are interested in getting access to set up CI so we can ensure this doesn't regress, I'd be happy to work with you on that, but don't have time to do so myself!

**Comment by Vertexwahn** [comment]
I can confirm testing. I used Visual Studio 2019 on Windows 10 x64.

**Comment by nelhage** [comment]
Thanks!

**Pull request merged**
