### PR TITLE
feat: add support for modules

### PR DESCRIPTION
**Pull request by TendTo**
This is a first draft to add support for the new Module system that is becoming the standard for bazel.
It seems to pass all the tests at least on my machine, but I haven't really tested on different architectures yet.

### Doubts

- will renovate be able to update the dependencies in this form?
- should the repo names remain unchanged or should they be dropped for the new, slimmer, module names?
   e. g. `com_github_facebook_zstd` -> `zstd` 
    - This also concerns this package, that could go from `com_github_nelhage_rules_boost` to `rules_boost`
- is support for different boost versions is something you want in your package?

[ closes #482 ]

### CODE REVIEW

**Comment by finn-ball** [comment]
How does this significantly differ from this earlier PR?
https://github.com/nelhage/rules_boost/pull/553

**Comment by TendTo** [comment]
It's been a while since I created this pr, and it was because I needed this module version for one of my projects and the other PR was lacking some features I needed. 

Mainly the boost version selection, as you noticed, and the ability to force only static boost compilation. 
This latter option is not in the pr, but in another [branch of the fork](https://github.com/TendTo/rules_boost/commits/link_static/), since I'm not sure it is the right way to do things but I worked pretty well for me.

I think that the version selection feature can be easily implemented in the other pr, before or after the merge.

**Comment by finn-ball** [comment]
It would be nice to get this project ported over. It's fairly popular and I have a downstream PR which could depend on a port in `rules_ros`.

**Comment by TendTo** [comment]
Feel free to close this pr. When you merge the other one I can open another one to add the feature.
Or @finn-ball may want to add it now.

**Comment by Vertexwahn** [comment]
Thanks for your contribution!

Moving to Bzlmod was finally performed in https://github.com/nelhage/rules_boost/pull/553

If we should overtalk something from this PR pleas open a new PR!

**Pull request closed without merging**
