### PR TITLE
Ubuntu 20.04 build CI build job

### PR DESCRIPTION
**Pull request by Vertexwahn**
Add Ubuntu 20.04 build CI build job

### CODE REVIEW

**Comment by cpsauer** [comment]
LGTM--merging. Thanks so much, @Vertexwahn, for all your work making things better.

[Async for @nelhage: Heads about the broken circleci thing that keeps showing up. Any chance you could take a peek at that?]

**Comment by nelhage** [comment]
I've tried re-authorizing with CircleCI … we'll see if that helps.

**Comment by cpsauer** [comment]
Yay! Thanks :)

**Comment by cpsauer** [comment]
Still failing but in a new way. Example: https://app.circleci.com/pipelines/github/nelhage/rules_boost/476/workflows/942c6829-8b54-4bab-8b23-77dbf394a84c/jobs/733

**Comment by cpsauer** [comment]
Took a quick shot at fixing circleci over in https://github.com/nelhage/rules_boost/pull/391, but something's still weird on clone, and I've got to bounce for now. @nelhage (or @Vertexwahn), could I get you to take a look and hand off, since this isn't really an area I know anything about yet?

**Comment by nelhage** [comment]
Okay, I also deleted an recreated the project on Circle and that seems to have resolved it! Just merged #391 with green status checks.

**Comment by cpsauer** [comment]
Sweet! Thanks guys

**Pull request merged**
