### PR TITLE
Update to boost 1.66 & fixes

### PR DESCRIPTION
**Pull request by russelltg**
Updated to latest boost (1.66) and added new libraries.

* add lzma because boost.iostreams requries it
* removal of tr1 (http://www.boost.org/users/history/version_1_65_0.html#version_1_65_0.removed_libraries)
* add winapi library which is required by Boost.Beast, but is private
* Add visibility attribute to `boost_library` to allow winapi to be private
* add asio_test, which made me discover that `-lpthread` was required for asio, which was added
* add new boost libraries (with tests):
  * Beast
  * callable_traits
  * mp11
  * process
  * winapi
* add make_unique.hpp header to Boost.Smart_ptr

### CODE REVIEW

**Comment by russelltg** [comment]
Hmm that's strange, that download works fine for me `bazel buid fetch --expunge && bazel build test //...`

**Comment by nelhage** [comment]
We had a lot of problems with sourceforce download links previously (for boost itself), as well as with pinning a single mirror (single sf.net mirrors don't have the best reliability). I'd love to find an alternative…

**Comment by russelltg** [comment]
It's interesting...it (sourceforge links) works fine on my computer. 

I am using the latest bazel (0.9) and you're using 0.7. I wonder if we updated it'd work? 

I'll throw down a test commit.

**Comment by russelltg** [comment]
Any reason you're using `native.new_http_archive` and not just `new_http_archive`? 

`new_http_archive` allows for listing multiple mirrors, which would alleviate the problem.

**Comment by nelhage** [comment]
Any opinions on excluding `"libs/iostreams/src/lzma.cpp"` and dropping lzma entirely? https://tukaani.org/lzma/ claims it's legacy/deprecated, although I don't know whether or not anyone needs it.

**Comment by russelltg** [comment]
I'll see if it works...I've never see `native.new_http_archive` before.

**Comment by nelhage** [comment]
`native.new_http_archive`, AIUI, is just how you access the built-in `new_http_archive` from inside a `.bzl` file (as opposed to a at top-level)

**Comment by russelltg** [comment]
Ok. I'll also look into using the non-deprecated library or dropping support.

**Comment by russelltg** [comment]
Hmm, I'm pretty sure I was using the non-deprecated version already....

**Comment by nelhage** [comment]
https://github.com/nelhage/rules_boost/commit/no-lzma seems to work locally fwiw although let's see what CI says.

I'm not particularly opposed to LZMA, just a bit worried that we had a bunch of flakiness with sf.net download URLs earlier.

**Comment by russelltg** [comment]
Is this an acceptable solution?

**Comment by russelltg** [comment]
For the record, I'd also be ok wit no lzma if you'd prefer that. 
I don't actually use it, I just felt like fixing it :)

**Comment by nelhage** [comment]
I'm willing to give this a try!

**Pull request merged**
